// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package parameters

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9f1b7427DecodeOtusRecipeAppApiParameters(in *jlexer.Lexer, out *RecipeCreateParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "cooking_time":
			out.CookingTime = int(in.Int())
		case "calories":
			out.Calories = int(in.Int())
		case "proteins":
			out.Proteins = int(in.Int())
		case "fats":
			out.Fats = int(in.Int())
		case "carbohydrates":
			out.Carbohydrates = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9f1b7427EncodeOtusRecipeAppApiParameters(out *jwriter.Writer, in RecipeCreateParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"cooking_time\":"
		out.RawString(prefix)
		out.Int(int(in.CookingTime))
	}
	{
		const prefix string = ",\"calories\":"
		out.RawString(prefix)
		out.Int(int(in.Calories))
	}
	{
		const prefix string = ",\"proteins\":"
		out.RawString(prefix)
		out.Int(int(in.Proteins))
	}
	{
		const prefix string = ",\"fats\":"
		out.RawString(prefix)
		out.Int(int(in.Fats))
	}
	{
		const prefix string = ",\"carbohydrates\":"
		out.RawString(prefix)
		out.Int(int(in.Carbohydrates))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RecipeCreateParams) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9f1b7427EncodeOtusRecipeAppApiParameters(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RecipeCreateParams) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9f1b7427EncodeOtusRecipeAppApiParameters(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RecipeCreateParams) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9f1b7427DecodeOtusRecipeAppApiParameters(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RecipeCreateParams) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9f1b7427DecodeOtusRecipeAppApiParameters(l, v)
}
