// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Recipe struct {
	ID          int64          `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	// Time for cooking in minutes
	CookingTime int16 `db:"cooking_time" json:"cooking_time"`
	// Dish calories in kcal
	Calories sql.NullInt32 `db:"calories" json:"calories"`
	// Dish fats in grams
	Proteins sql.NullInt32 `db:"proteins" json:"proteins"`
	// Dish fats in grams
	Fats sql.NullInt32 `db:"fats" json:"fats"`
	// Dish carbohydrates in grams
	Carbohydrates sql.NullInt32 `db:"carbohydrates" json:"carbohydrates"`
	Rating        string        `db:"rating" json:"rating"`
	VoteCount     int32         `db:"vote_count" json:"vote_count"`
	VoteSum       int32         `db:"vote_sum" json:"vote_sum"`
	Version       uuid.UUID     `db:"version" json:"version"`
}
